### ISSUE TITLE
[Bug]: Error do not Load games -  Version: 2.5.1.0

### ISSUE THREAD

**Issue by jonetu** [Fumo-Unlockers/Xbox-Achievement-Unlocker#230]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the settings page)?

2.5.1.0

### Tool Section

Games

### What is the bug?

Information
=================================
Tool Version: 2.5.1.0
System Version: 10.0.22631.0
Tool Uptime: 00:00:29.8810472
=================================
Exception
=================================
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at XAU.ViewModels.Pages.GamesViewModel.AddGame(Int32 index)
   at XAU.ViewModels.Pages.GamesViewModel.FilterGames()
   at XAU.ViewModels.Pages.GamesViewModel.LoadGame()
   at XAU.ViewModels.Pages.GamesViewModel.GetGamesList()
   at XAU.ViewModels.Pages.GamesViewModel.InitializeViewModel()
   at XAU.ViewModels.Pages.GamesViewModel.OnNavigatedTo()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by ItsLogic** [comment]
can you send me your xuid or gamertag so I can reproduce?

**Comment by jonetu** [comment]
XUID: 2535457079090126
